[package]
name = "cramp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cod = { git = "https://github.com/kyllingene/cod.git" }
crossbeam-channel = "0.5.6"
dbus = { version = "0.9", features = ["futures"]}
dbus-crossroads = "0.5"
dbus-tree = "0.9.2"
rand = "0.8.5"
rodio = "0.17"
termion = "2.0"
